name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Use GitVersion
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.1.2
        dotnet-gitversion /output buildserver /nofetch
    - name: Install dependencies
      run: dotnet restore --configuration Release
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: |
          AutofacContrib.NSubstitute/bin/Release/*.nupkg
          AutofacContrib.NSubstitute/bin/Release/*.snupkg
